### ISSUE TITLE
We can use dishy.starlink.com as default address

### ISSUE THREAD

**Issue by Punkoivan** [ewilken/starlink-exporter#2]
Hello there!
Thank you for the exporter.

We can use dishy.starlink.com as default address instead of  192.168.100.1 to mitigate usage of host network with docker.

That will allow to use exporter with docker compose inside docker network.
Does that make sense?

Thanks,
Ivan

**Comment by ewilken** [comment]
Interesting! Does the dish resolve dishy.starlink.com to its own IP? I'm currently not on my Starlink network, so I can't test.

**Comment by Punkoivan** [comment]
Yup:
```
punko@punko:~/projects/starlink-metrics/starlink_metrics$ dig dishy.starlink.com A +short
192.168.100.1
```

Also you can visit dishy.starlink.com and you'll be able to see statistics, almost identical to the one in app, including network devices etc.

**Comment by ewilken** [comment]
That's super cool, didn't know that, thank you! 🙂 Feel free to send a PR changing it. Otherwise I can do it later.

**Comment by Punkoivan** [comment]
Will try to send it today, it seems easy even for me with almost no experience in Rust.
